"""delete email & phone

Revision ID: 24cecbb99d8d
Revises: 2877440c93ca
Create Date: 2024-05-13 23:44:23.260690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24cecbb99d8d"
down_revision: Union[str, None] = "2877440c93ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "email")
    op.drop_column("user", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "user", sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
