"""add decimal places to decimal

Revision ID: 5c16d74fce5f
Revises: 40ae962665ca
Create Date: 2024-05-06 09:14:03.282490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c16d74fce5f'
down_revision: Union[str, None] = '40ae962665ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=2),
               existing_nullable=False)
    op.alter_column('orderdetails', 'line_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=2),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Numeric(scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('orderdetails', 'line_total',
               existing_type=sa.Numeric(scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('order', 'total_amount',
               existing_type=sa.Numeric(scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
